Kütüphaneler

In [45]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix

Veri Ön İşleme

In [46]:
veriler = pd.read_csv("../veri/veriler.csv")
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [47]:
x = veriler.iloc[:,1:4]
y = veriler.iloc[:,4:].values

Verilerin eğitim ve test için bölünmesi

In [48]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

Verilerin ölçeklenmesi

In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test) 

1. Logistic Regression

In [50]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train,y_train.ravel())
y_pred = logr.predict(X_test)

print(y_pred)
print(y_test.T[0])
cm = confusion_matrix(y_test, y_pred)
print(cm)

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
[[0 1]
 [7 0]]


2. KNN

In [51]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1, metric="minkowski")
knn.fit(X_train, y_train.ravel())
y_pred = knn.predict(X_test)

print(y_pred)
print(y_test.T[0])
cm = confusion_matrix(y_test, y_pred)
print(cm)

['k' 'k' 'e' 'k' 'e' 'k' 'k' 'k']
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
[[1 0]
 [1 6]]


3. SVC (SVM Classifier)

In [52]:
from sklearn.svm import SVC
svc = SVC(kernel="poly")
svc.fit(X_train, y_train.ravel() )
y_pred = svc.predict(X_test)

print(y_pred)
print(y_test.T[0])
cm = confusion_matrix(y_test, y_pred)
print(cm)

['e' 'e' 'e' 'e' 'e' 'e' 'e' 'e']
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
[[1 0]
 [7 0]]


4. Naive Bayes

In [53]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train.ravel())
y_pred = gnb.predict(X_test)

print(y_pred)
print(y_test.T[0])
cm = confusion_matrix(y_test, y_pred)
print(cm)

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'k']
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
[[0 1]
 [6 1]]


5. Decision tree

In [54]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion="entropy")
dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)

print(y_pred)
print(y_test.T[0])
cm = confusion_matrix(y_test, y_pred)
print(cm)

['e' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
[[1 0]
 [1 6]]


6. Random Forest

In [55]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10, criterion = "entropy")
rfc.fit(X_train, y_train.ravel())
y_pred = rfc.predict(X_test)
print(y_pred)
print(y_test.T[0])
cm = confusion_matrix(y_test, y_pred)
print(cm)

['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
[[1 0]
 [0 7]]


In [58]:

y_proba = rfc.predict_proba(X_test)
print(y_proba.T)
print(y_test.T[0])

[[0.4 0.2 0.2 0.2 0.5 0.2 0.2 0.4]
 [0.6 0.8 0.8 0.8 0.5 0.8 0.8 0.6]]
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']


In [57]:
from sklearn.metrics import roc_curve
fpr,tpr, thold =  roc_curve(y_test, y_proba[:,0], pos_label="e")
print(fpr)
print(tpr)
print(thold)

[0.         0.         0.28571429 1.        ]
[0. 1. 1. 1.]
[1.5 0.5 0.4 0.2]
