In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
veriler = pd.read_csv("../veri/tenis.csv")
veriler.head(3)

outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes

In [43]:
play = veriler.iloc[:, -1:].values
play.T

array([['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes',
        'yes', 'yes', 'yes', 'no']], dtype=object)

In [44]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

veriler2 = veriler.apply(LabelEncoder().fit_transform)
veriler2

outlook  temperature  humidity  windy  play
0         2           11         4      0     0
1         2            8         6      1     0
2         0           10         5      0     1
3         1            4         9      0     1
4         1            2         3      0     1
5         1            1         1      1     0
6         0            0         0      1     1
7         2            6         8      0     0
8         2            3         1      0     1
9         1            7         3      0     1
10        2            7         1      1     1
11        0            6         6      1     1
12        0            9         2      0     1
13        1            5         7      1     0

In [45]:
c = veriler2.iloc[:,:1]
ohe = OneHotEncoder()
c = ohe.fit_transform(c).toarray()
c

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [46]:
havadurumu = pd.DataFrame(data=c, index=range(14), columns=["o","r","s"])
havadurumu


o    r    s
0   0.0  0.0  1.0
1   0.0  0.0  1.0
2   1.0  0.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   1.0  0.0  0.0
7   0.0  0.0  1.0
8   0.0  0.0  1.0
9   0.0  1.0  0.0
10  0.0  0.0  1.0
11  1.0  0.0  0.0
12  1.0  0.0  0.0
13  0.0  1.0  0.0

In [47]:
sonveriler = pd.concat([havadurumu, veriler.iloc[ : , 1 :3 ]], axis=1)
sonveriler

o    r    s  temperature  humidity
0   0.0  0.0  1.0           85        85
1   0.0  0.0  1.0           80        90
2   1.0  0.0  0.0           83        86
3   0.0  1.0  0.0           70        96
4   0.0  1.0  0.0           68        80
5   0.0  1.0  0.0           65        70
6   1.0  0.0  0.0           64        65
7   0.0  0.0  1.0           72        95
8   0.0  0.0  1.0           69        70
9   0.0  1.0  0.0           75        80
10  0.0  0.0  1.0           75        70
11  1.0  0.0  0.0           72        90
12  1.0  0.0  0.0           81        75
13  0.0  1.0  0.0           71        91

In [48]:
sonveriler = pd.concat([sonveriler, veriler2.iloc[:,-2:]],axis=1)
sonveriler

o    r    s  temperature  humidity  windy  play
0   0.0  0.0  1.0           85        85      0     0
1   0.0  0.0  1.0           80        90      1     0
2   1.0  0.0  0.0           83        86      0     1
3   0.0  1.0  0.0           70        96      0     1
4   0.0  1.0  0.0           68        80      0     1
5   0.0  1.0  0.0           65        70      1     0
6   1.0  0.0  0.0           64        65      1     1
7   0.0  0.0  1.0           72        95      0     0
8   0.0  0.0  1.0           69        70      0     1
9   0.0  1.0  0.0           75        80      0     1
10  0.0  0.0  1.0           75        70      1     1
11  1.0  0.0  0.0           72        90      1     1
12  1.0  0.0  0.0           81        75      0     1
13  0.0  1.0  0.0           71        91      1     0

In [53]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(sonveriler.iloc[:, :-1], sonveriler.iloc[:,-1:] , test_size=0.33 , random_state=0 )

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

In [54]:
y_test.T

8   6   4   11  2 
play   1   1   1   1   1

In [55]:
y_pred.T

array([[0.74233631, 0.75371988, 0.78998557, 0.27181229, 0.78572451]])

In [56]:
import statsmodels.api as sm

X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1)

X_l = sonveriler.iloc[:, [1,2,3,4,5]].values
X_l = np.array(X_l, dtype=float)

model = sm.OLS(sonveriler.iloc[:,-1:].values, X_l).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.738
Model:                            OLS   Adj. R-squared (uncentered):              0.593
Method:                 Least Squares   F-statistic:                              5.071
Date:                Thu, 28 Jul 2022   Prob (F-statistic):                      0.0174
Time:                        14:30:01   Log-Likelihood:                         -7.3955
No. Observations:                  14   AIC:                                      24.79
Df Residuals:                       9   BIC:                                      27.99
Df Model:                           5                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

c:\Users\OmerYildiz\anaconda3\envs\makineogrenmesi\lib\site-packages\scipy\stats\_stats_py.py:1477: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [57]:
X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1)

X_l = sonveriler.iloc[:, [2,3,4,5]].values
X_l = np.array(X_l, dtype=float)

model = sm.OLS(sonveriler.iloc[:,-1:].values, X_l).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.729
Model:                            OLS   Adj. R-squared (uncentered):              0.620
Method:                 Least Squares   F-statistic:                              6.715
Date:                Thu, 28 Jul 2022   Prob (F-statistic):                     0.00683
Time:                        14:30:48   Log-Likelihood:                         -7.6409
No. Observations:                  14   AIC:                                      23.28
Df Residuals:                      10   BIC:                                      25.84
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

c:\Users\OmerYildiz\anaconda3\envs\makineogrenmesi\lib\site-packages\scipy\stats\_stats_py.py:1477: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [60]:
X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1)

X_l = sonveriler.iloc[:, [2,3,4]].values
X_l = np.array(X_l, dtype=float)

model = sm.OLS(sonveriler.iloc[:,-1:].values, X_l).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.714
Model:                            OLS   Adj. R-squared (uncentered):              0.636
Method:                 Least Squares   F-statistic:                              9.170
Date:                Thu, 28 Jul 2022   Prob (F-statistic):                     0.00250
Time:                        14:32:59   Log-Likelihood:                         -8.0011
No. Observations:                  14   AIC:                                      22.00
Df Residuals:                      11   BIC:                                      23.92
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

c:\Users\OmerYildiz\anaconda3\envs\makineogrenmesi\lib\site-packages\scipy\stats\_stats_py.py:1477: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [65]:
X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1)

X_l = sonveriler.iloc[:, [2,3]].values
X_l = np.array(X_l, dtype=float)

model = sm.OLS(sonveriler.iloc[:,-1:].values, X_l).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.687
Model:                            OLS   Adj. R-squared (uncentered):              0.635
Method:                 Least Squares   F-statistic:                              13.16
Date:                Thu, 28 Jul 2022   Prob (F-statistic):                    0.000942
Time:                        14:34:06   Log-Likelihood:                         -8.6434
No. Observations:                  14   AIC:                                      21.29
Df Residuals:                      12   BIC:                                      22.56
Df Model:                           2                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

c:\Users\OmerYildiz\anaconda3\envs\makineogrenmesi\lib\site-packages\scipy\stats\_stats_py.py:1477: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [67]:
sonveriler.iloc[:, [2,3]]

s  temperature
0   1.0           85
1   1.0           80
2   0.0           83
3   0.0           70
4   0.0           68
5   0.0           65
6   0.0           64
7   1.0           72
8   1.0           69
9   0.0           75
10  1.0           75
11  0.0           72
12  0.0           81
13  0.0           71

In [68]:
x_train, x_test, y_train, y_test = train_test_split(sonveriler.iloc[:, [2,3]], sonveriler.iloc[:,-1:], test_size=0.33, random_state=0)

regressor = LinearRegression()
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

In [69]:
y_test.T

8   6   4   11  2 
play   1   1   1   1   1

In [71]:
y_pred.T

array([[0.03358209, 0.39800995, 0.49419569, 0.59038143, 0.85489221]])