Kütüphaneler


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Veri Ön İşleme

In [2]:
veriler = pd.read_csv("../veri/veriler.csv")
veriler.head()

ulke  boy  kilo  yas cinsiyet
0   tr  130    30   10        e
1   tr  125    36   11        e
2   tr  135    34   10        k
3   tr  133    30    9        k
4   tr  129    38   12        e

In [3]:
x = veriler.iloc[:, 1:4].values
y = veriler.iloc[:, 4:].values

Verilerin eğitim ve test olarak bölünmesi

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

Verilerin ölçeklenmesi

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [6]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train, y_train.ravel()) 

LogisticRegression(random_state=0)

In [7]:
y_pred = logr.predict(X_test)
print(y_pred)
print(y_test.T[0])

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']


In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[0 1]
 [7 0]]


In [9]:
(cm[0][0]+cm[1][1])/len(y_test)

0.0

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric="minkowski") 
knn.fit(X_train, y_train.ravel())
y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred) 
cm

array([[0, 1],
       [6, 1]], dtype=int64)

In [19]:
knn = KNeighborsClassifier(n_neighbors=1, metric="minkowski") 
knn.fit(X_train, y_train.ravel())
y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred) 
cm

array([[1, 0],
       [1, 6]], dtype=int64)